### ISSUE TITLE
iOS Not all asset views lie inside the native ad view

### ISSUE THREAD

**Issue by PlymouthRock** [sakebook/flutter_native_ads#22]
Ads are working on our iOS device.  We are getting this error message in the debug log.  Not sure if we are causing this or if it is from the plugin:

<Google> <Google:HTML> Not all asset views lie inside the native ad view. This indicates an integration problem. Such implementations will not be supported in the future. Please make sure that all native ad assets are rendered inside the native ad view.

**Comment by sakebook** [comment]
I think probably the following problems.

- Insufficient NativeAdView rendering area
- No support some field (like an icon) yet.

**Comment by sakebook** [comment]
Release 0.3.0

Supported all fields.

https://github.com/sakebook/flutter_native_ads/blob/master/CHANGELOG.md#030
