### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs.

### ISSUE THREAD

**Issue by PlymouthRock** [sakebook/flutter_native_ads#24]
Getting the following message submitting our app to Apple App Store:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect. 

This is a known issue with the ADMob iOS SDK: https://groups.google.com/forum/#!topic/google-admob-ads-sdk/QuZMbjIyxn8

It looks like this has been resolved in the 7.50 SDK.

**Comment by sakebook** [comment]
Thank you for the notice. I will fix it.

**Comment by sakebook** [comment]
@PlymouthRock 

Supported 0.2.1.

https://github.com/sakebook/flutter_native_ads/blob/master/CHANGELOG.md#021
