### ISSUE TITLE
Ads wont show if using my own AdUnity ID, but if using test ads ID it's fine...

### ISSUE THREAD

**Issue by zukinaru** [sakebook/flutter_native_ads#26]
Hi,

Ads won't show if using my Admob ID, but if using test ads it's fine...

I just get the error: `{errorCode: 3}`

any idea?

**Comment by sakebook** [comment]
The meaning of error code 3 is that there are no ads to retrieve.

The request is correct.

https://stackoverflow.com/questions/33566485/failed-to-load-ad-3

**Comment by zukinaru** [comment]
is there a way to implement,

if `onAdFailedToLoad` is triggered then widget to be able to destroy or replaced by another image (custom ads) ?

currently, if ads failed, i just blank white screen, this generate wasteful space...

Thanks In Advance...

**Comment by sakebook** [comment]
I think it can be realized by using Provider.

https://pub.dev/packages/provider

Also, I thought it would be useful to have a fail back widget. so I'll create issue.
