### ISSUE TITLE
Ad failed to load on iOS, error 11, Request Error: Internal error

### ISSUE THREAD

**Issue by Greatcallie** [sakebook/flutter_native_ads#37]
Its working on Android but failed to work on iOS repeatedly even with test ad unit. it gives the error message:
error code: 11, Request Error: Internal error

**Comment by sakebook** [comment]
Error on AdMob side.

I recommend checking with the actual machine.

https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode#/c:@E@GADErrorCode@kGADErrorInternalError

**Comment by Greatcallie** [comment]
I just noticed that the didReceive ad is also called with the loaded ad
after the ad failure call. But however the ad isn't showing. What could be
the problem?

**Comment by Greatcallie** [comment]
The example project is also not working. Could you test it and ensure it's
not broken?

**Comment by sakebook** [comment]
I found bug. Will fix.

**Comment by sakebook** [comment]
Please use v0.4.0
