### ISSUE TITLE
How can I make a smaller ad view ?

### ISSUE THREAD

**Issue by sunjianan9900** [sakebook/flutter_native_ads#40]
like this 
<img width="449" alt="WX20191227-144332@2x" src="https://user-images.githubusercontent.com/10936316/71505217-5fd2d400-28b7-11ea-8a36-6d0608951f7c.png">

But I found Media is Required on the README

**Comment by sakebook** [comment]
It is can't yet.

But I was supported icon. So media become to optional.

I do higher priority.

**Comment by sakebook** [comment]
Please use v0.4.0
