### ISSUE TITLE
Layout is not visible on Release build

### ISSUE THREAD

**Issue by rajeshjeshar** [sakebook/flutter_native_ads#48]
Shows container instead of layout,but debugging one is showing well.
Created my own layouts and also tested your Example code,but nothing is showing in release mode

**Comment by sakebook** [comment]
Please show me flutter log. And does this happen which on Android or iOS?

**Comment by rajeshjeshar** [comment]
@sakebook  It does not logs anything,and Ive never tried on Ios,it happens only on Android.
Debugging is working superb,the release build the widget is simply white

**Comment by WolfTheZelda** [comment]
I'm also having the same problem, it was working normally in the debug and release, but now the widget only renders a blank space

**Comment by ale-getman** [comment]
Same problem

**Comment by matthewrice345** [comment]
I added the following to my proguard-rules.pro and Ads show up in release. 

`## Admob
-keep public class com.google.firebase.analytics.FirebaseAnalytics {
    public *;
}

-keep public class com.google.android.gms.measurement.AppMeasurement {
    public *;
}`
