### ISSUE TITLE
onAdFailedToLoad!!! {errorCode: 3}

### ISSUE THREAD

**Issue by AnhTu6610** [sakebook/flutter_native_ads#49]
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(25192): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(25192): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(25192): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(25192): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(25192): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@60eba24
D/FlutterActivityAndFragmentDelegate(25192): Executing Dart entrypoint: main, and sending initial route: /
Syncing files to device AOSP on IA Emulator...
D/EGL_emulation(25192): eglMakeCurrent: 0xdf4051e0: ver 2 0 (tinfo 0xdf403660)
I/utideas.diyjav(25192): The ClassLoaderContext is a special shared library.
I/utideas.diyjav(25192): The ClassLoaderContext is a special shared library.
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 0 (0) 1 0
I/utideas.diyjav(25192): The ClassLoaderContext is a special shared library.
I/DynamiteModule(25192): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21200
I/DynamiteModule(25192): Selected remote version of com.google.android.gms.ads.dynamite, version >= 21200
D/DynamitePackage(25192): Instantiated singleton DynamitePackage.
D/DynamitePackage(25192): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
D/NetworkSecurityConfig(25192): No Network Security Config specified, using platform default
I/WebViewFactory(25192): Loading com.android.chrome version 69.0.3497.100 (code 349710017)
I/utideas.diyjav(25192): The ClassLoaderContext is a special shared library.
I/cr_LibraryLoader(25192): Time to load native libraries: 32 ms (timestamps 3533-3565)
E/cr_VariationsUtils(25192): Failed reading seed file "/data/user/0/com.tutideas.diyjava/app_webview/variations_seed": /data/user/0/com.tutideas.diyjava/app_webview/variations_seed (No such file or directory)
I/chromium(25192): [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(25192): Expected native library version number "69.0.3497.100", actual native library version number "69.0.3497.100"
W/cr_ChildProcLH(25192): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup(25192): Initializing chromium process, singleProcess=false
I/utideas.diyjav(25192): Background concurrent copying GC freed 16356(1761KB) AllocSpace objects, 11(240KB) LOS objects, 49% free, 2MB/4MB, paused 6.787ms total 273.730ms
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/utideas.diyjav(25192): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/cr_media(25192): Requires BLUETOOTH permission
D/HostConnection(25192): HostConnection::get() New Host Connection established 0xdf423d10, tid 25265
D/HostConnection(25192): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
E/chromium(25192): [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
W/cr_CrashFileManager(25192): /data/user/0/com.tutideas.diyjava/cache/WebView/Crash Reports does not exist or is not a directory
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(25192): eglCreateContext: 0xdf407b80: maj 2 min 0 rcv 2
D/EGL_emulation(25192): eglMakeCurrent: 0xdf407b80: ver 2 0 (tinfo 0xc147f9b0)
W/VideoCapabilities(25192): Unrecognized profile 4 for video/hevc
I/VideoCapabilities(25192): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil(25192): HW encoder for video/avc is not available on this device.
E/chromium(25192): [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(25192): eglCreateContext: 0xb749b960: maj 2 min 0 rcv 2
D/EGL_emulation(25192): eglMakeCurrent: 0xb749b960: ver 2 0 (tinfo 0xc147f9b0)
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 1 (1) 0 0
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 2 (2) 0 0
D/eglCodecCommon(25192): setVertexArrayObject: set vao to 1 (1) 0 0
E/utideas.diyjav(25192): Invalid ID 0x00000000.
E/MethodChannel#flutter/platform_views(25192): Failed to handle method call
E/MethodChannel#flutter/platform_views(25192): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/MethodChannel#flutter/platform_views(25192): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
E/MethodChannel#flutter/platform_views(25192): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2155)
E/MethodChannel#flutter/platform_views(25192): 	at android.content.res.Resources.getLayout(Resources.java:1155)
E/MethodChannel#flutter/platform_views(25192): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
E/MethodChannel#flutter/platform_views(25192): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/MethodChannel#flutter/platform_views(25192): 	at android.view.View.inflate(View.java:24354)
E/MethodChannel#flutter/platform_views(25192): 	at sakebook.github.com.native_ads.UnifiedAdLayout.<init>(UnifiedAdLayout.kt:22)
E/MethodChannel#flutter/platform_views(25192): 	at sakebook.github.com.native_ads.UnifiedAdLayoutFactory.create(UnifiedAdLayoutFactory.kt:11)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/MethodChannel#flutter/platform_views(25192): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
E/MethodChannel#flutter/platform_views(25192): 	at android.app.Dialog.show(Dialog.java:302)
E/MethodChannel#flutter/platform_views(25192): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(25192): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(25192): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(25192): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(25192): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter/platform_views(25192): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter/platform_views(25192): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(25192): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter/platform_views(25192): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (25192): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Resource ID #0x0, null)
E/flutter (25192): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (25192): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (25192): <asynchronous suspension>
E/flutter (25192): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (25192): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (25192): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (25192): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (25192): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (25192): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (25192): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (25192): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (25192): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #15     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
E/flutter (25192): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #17     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (25192): #18     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (25192): #19     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (25192): #20     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (25192): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #25     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (25192): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (25192): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25192): #42     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
E/flutter (25192): #43     RenderObject.layout (package:flutt

**Comment by sakebook** [comment]
Maybe same #26.
