### ISSUE TITLE
[ios] Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by furkansarihan** [sakebook/flutter_native_ads#56]
This error caused to app crash running on both emulator and real ios device with internet connection.
App doesn’t crash without internet. It happens after ad request.

nativeAd object isn’t nil.

What was happened?

![Screen Shot 2020-07-02 at 15 32 53](https://user-images.githubusercontent.com/27918319/86359317-82381680-bc79-11ea-85eb-c185294e7dd5.png)

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale
    en)
    • Flutter version 1.18.0-11.1.pre at /Users/fusarihan/dev/flutter
    • Framework revision 2738a1148b (7 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/fusarihan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • F • 1d3aa0502670fba6e59b70d4a46bcc67d4fa5c57 • ios • iOS 13.4.1

• No issues found!
```

**Comment by beagle-barks** [comment]
Have the same problem. I've tried unwrapping  `nativeAd` and `headline` before, but it did not help.

**Comment by beagle-barks** [comment]
Having the same issue!

Replacing
```
headlineView.text = nativeAd.headline
bodyView.text = nativeAd.body
callToActionView.text = nativeAd.callToAction
```

with

```
guard let headline = nativeAd.headline else { return; }
headlineView.text = headline
bodyView.text = body
callToActionView.text = callToAction
```

solved it!

**Comment by kevintesar** [comment]
I'm having the same issue

**Comment by furkansarihan** [comment]
@kevintesar  Can you load ads? Maybe there is a mistake on configurations.

**Comment by melodysdreamj** [comment]
just move  Bundle.main.loadNibNamed part to init. then fix this issue.

original
`    
init(frame: CGRect, viewId: Int64, args: [String: Any], messeneger: FlutterBinaryMessenger) {
        self.args = args
        self.messeneger = messeneger
        self.frame = frame
        self.viewId = viewId
        self.placementId = self.args["placement_id"] as! String
        self.layoutName = self.args["layout_name"] as! String
        self.attributionText = self.args["text_attribution"] as! String

        self.adLoader = GADAdLoader(adUnitID: placementId, rootViewController: nil,
                    adTypes: [ .unifiedNative ], options: nil)
        channel = FlutterMethodChannel(name: "com.github.sakebook.ios/unified_ad_layout_\(viewId)", binaryMessenger: messeneger)
        super.init()
        fetchAd()
    }
    
    private func fetchAd() {
        adLoader.delegate = self
        let request = GADRequest()
        adLoader.load(request)
    }
    
    func view() -> UIView {
        guard let nibObjects = Bundle.main.loadNibNamed(layoutName, owner: nil, options: nil),
            let adView = nibObjects.first as? GADUnifiedNativeAdView else {
                fatalError("Could not load nib file for adView")
        }
        unifiedNativeAdView = adView
        headlineView = adView.headlineView as? UILabel
        bodyView = adView.bodyView as? UILabel
        callToActionView = adView.callToActionView as? UILabel
        mediaView = adView.mediaView
        guard let attributionLabel = (adView as UIView).subviews.first(where: { (v) -> Bool in
            v.restorationIdentifier == "flutter_native_ad_attribution_view_id"
        }) as? UILabel else {
            fatalError("Could not find Restoration ID 'flutter_native_ad_attribution_view_id'")
        }
        attributionView = attributionLabel
        
        iconView = adView.iconView as? UIImageView
        starRatingView = adView.starRatingView as? UILabel
        storeView = adView.storeView as? UILabel
        priceView = adView.priceView as? UILabel
        advertiserView = adView.advertiserView as? UILabel
        
        return unifiedNativeAdView
    }
`



fixed 
`    init(frame: CGRect, viewId: Int64, args: [String: Any], messeneger: FlutterBinaryMessenger) {
        self.args = args
        self.messeneger = messeneger
        self.frame = frame
        self.viewId = viewId
        self.placementId = self.args["placement_id"] as! String
        self.layoutName = self.args["layout_name"] as! String
        self.attributionText = self.args["text_attribution"] as! String

        self.adLoader = GADAdLoader(adUnitID: placementId, rootViewController: nil,
                    adTypes: [ .unifiedNative ], options: nil)
        channel = FlutterMethodChannel(name: "com.github.sakebook.ios/unified_ad_layout_\(viewId)", binaryMessenger: messeneger)
        super.init()
        
        guard let nibObjects = Bundle.main.loadNibNamed(layoutName, owner: nil, options: nil),
            let adView = nibObjects.first as? GADUnifiedNativeAdView else {
                fatalError("Could not load nib file for adView")
        }
        self.adView = adView;
        
        fetchAd()
    }
    var adView:GADUnifiedNativeAdView?
    
    private func fetchAd() {
        adLoader.delegate = self
        let request = GADRequest()
        adLoader.load(request)
    }
    
    func view() -> UIView {
        
        unifiedNativeAdView = adView
        headlineView = adView?.headlineView as? UILabel
        bodyView = adView?.bodyView as? UILabel
        callToActionView = adView?.callToActionView as? UILabel
        mediaView = adView?.mediaView
        guard let attributionLabel = (adView! as UIView).subviews.first(where: { (v) -> Bool in
            v.restorationIdentifier == "flutter_native_ad_attribution_view_id"
        }) as? UILabel else {
            fatalError("Could not find Restoration ID 'flutter_native_ad_attribution_view_id'")
        }
        attributionView = attributionLabel
        
        iconView = adView?.iconView as? UIImageView
        starRatingView = adView?.starRatingView as? UILabel
        storeView = adView?.storeView as? UILabel
        priceView = adView?.priceView as? UILabel
        advertiserView = adView?.advertiserView as? UILabel
        
        return unifiedNativeAdView
    }`
