### ISSUE TITLE
Define swift version

### ISSUE THREAD

**Issue by sakebook** [sakebook/flutter_native_ads#7]
https://github.com/sakebook/flutter_native_ads/issues/5#issuecomment-527849433

**Comment by NavneetSi** [comment]
it's resolved by adding 
ENV['SWIFT_VERSION'] = '4.2
in podfile
Now its working fine
![Screenshot 2019-09-04 at 5 15 24 PM](https://user-images.githubusercontent.com/54845982/64252147-c4000f80-cf37-11e9-9499-481704dbe002.png)
